Repository 9oormthon-2523/Ezz, pull requests merged in 2024-12, with the labels that each got.

#3 feat(studioPage): header UI 구현
  next.config.ts
  package-lock.json
  package.json
  public/studioPage/Camera.svg
  public/studioPage/Hamburger.svg
  public/studioPage/Logout.svg
  public/studioPage/MiniChzzk.svg
  public/studioPage/MyChannel.svg
  public/studioPage/Profile.svg
  public/studioPage/StudioText.svg
  public/studioPage/WhiteLogo.svg
  src/app/(route)/profile/[user]/.gitkeep
  src/app/(route)/studio/[user]/_components/ExpandNavButton.client.tsx
  src/app/(route)/studio/[user]/_components/Header.server.tsx
  src/app/(route)/studio/[user]/_components/HeaderButton.client.tsx
  src/app/(route)/studio/[user]/_components/MenuButtonBox.client.tsx
  src/app/(route)/studio/[user]/_components/ProfileButton.client.tsx
  src/app/(route)/studio/[user]/_components/ProfileMenu.server.tsx
  src/app/(route)/studio/[user]/page.tsx
  src/app/_components/OutsideClickWrapper.client.tsx
  src/app/_store/studio/useNavSizeToggle.client.ts
  src/app/_styles/studioPage.css
  tailwind.config.ts
  tsconfig.json
Labels: feat

#17 feat(login): 로그인 기능 구현
  package-lock.json
  package.json
  src/app/_components/.gitkeep
  src/app/_components/KakaoBtn.tsx
  src/app/_utils/.gitkeep
  src/app/_utils/supabase/client.ts
  src/app/_utils/supabase/server.ts
  src/app/api/auth/callback/route.ts
  src/app/api/auth/user/route.ts
Labels: feat

#19 feat(mainPage): 메인페이지 UI 및 header 공통 컴포넌트 구현
  src/app/(route)/(main)/_components/NavBar/NavBar.client.tsx
  src/app/(route)/(main)/_components/StreamCard/StreamCard.server.tsx
  src/app/(route)/(main)/_components/StreamList/StreamList.server.tsx
  src/app/(route)/(main)/_components/StreamList/dummy.ts
  src/app/(route)/(main)/page.tsx
  src/app/_components/Header/ExpandNavButton.client.tsx
  src/app/_components/Header/Header.server.tsx
  src/app/_components/Header/HeaderButton.client.tsx
  src/app/_components/Header/LoginButton.client.tsx
  src/app/_store/main/useNavToggle.client.ts
  src/app/_styles/header.css
Labels: feat, design

#18 feat(Channel page): 채널 페이지 전체 UI 구현
  src/app/(route)/[channel]/components/ChannelProfile.tsx
  src/app/(route)/[channel]/components/Post.tsx
  src/app/(route)/[channel]/layout.tsx
  src/app/(route)/[channel]/page.tsx
Labels: feat, design

#25 design(Studio page): 대시 보드 UI 구현
  public/studioPage/Canvas.svg
  public/studioPage/Document.svg
  public/studioPage/Pencill.svg
  public/studioPage/Robot.svg
  src/app/(route)/studio/[user]/components_suport/DashBoard.server.tsx
  src/app/(route)/studio/[user]/components_suport/DashBoardWidget/Widget1.server.tsx
  src/app/(route)/studio/[user]/components_suport/DashBoardWidget/Widget2.server.tsx
  src/app/(route)/studio/[user]/components_suport/DashBoardWidget/Widget3.server.tsx
  src/app/(route)/studio/[user]/components_suport/DashBoardWidget/Widget4.server.tsx
  src/app/(route)/studio/[user]/components_suport/DashBoardWidget/Widget5.server.tsx
  src/app/(route)/studio/[user]/components_suport/TestWireFrame.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardBox.server.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardButton.server.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardInfo.server.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardSection.server.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardTitle.server.tsx
  src/app/(route)/studio/[user]/components_suport/component/DashBoardWrapper.server.tsx
  src/app/(route)/studio/[user]/components_suport/studioWrapper.server.tsx
  src/app/(route)/studio/[user]/page.tsx
  src/app/_styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: design

#32 feat(component/footer): footer 공통 컴포넌트 구현
  src/app/_components/Footer/footer.tsx
Labels: feat, design

#35 feat(component/loginModal): 로그인 모달 구현
  public/loginModal/Logo.svg
  public/loginModal/close.svg
  public/loginModal/kakao.webp
  src/app/_components/Header/Header.server.tsx
  src/app/_components/Header/LoginButton.client.tsx
  src/app/_components/LoginModal/LoginModal.client.tsx
  src/app/_store/modal/useLoginModalToggle.cliet.ts
Labels: feat, design

#36 feat(studioPage): 페이지 전체 레이아웃 및 폴더 라우트 조정
  public/studioPage/ArrowDown.svg
  public/studioPage/ArrowUp.svg
  public/studioPage/Canvas.svg
  public/studioPage/Dashboard.svg
  public/studioPage/Document.svg
  public/studioPage/NavDept.svg
  public/studioPage/Pencill.svg
  public/studioPage/Robot.svg
  public/studioPage/Studio.svg
  public/studioPage/Viewer.svg
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardBox.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardButton.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardInfo.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardSection.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardTitle.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/DashBoardWrapper.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget1.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget2.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget3.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget4.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget5.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/page.tsx
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/_components/Header/ExpandNavButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/HeaderButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/Navigation.client.tsx
  src/app/(route)/studio/[uid]/_components/common/MenuButtonBox.client.tsx
  src/app/(route)/studio/[uid]/_components/common/StudioWrapper.server.tsx
  src/app/(route)/studio/[user]/_components/MenuButtonBox.client.tsx
  src/app/(route)/studio/[user]/page.tsx
  src/app/_styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: feat, design

#38 feat(studioPage): supabase auth를 이용한 라우트 기능 구현
  public/studioPage/Close.svg
  src/app/(route)/studio/[uid]/(route)/(dashboard)/page.tsx
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/Navigation.client.tsx
  src/app/(route)/studio/[uid]/_components/Popup/CheckBtn.client.tsx
  src/app/(route)/studio/[uid]/_components/Popup/Popup.server.tsx
  src/app/(route)/studio/[uid]/_components/common/ContentWrapper.client.tsx
  src/app/(route)/studio/[uid]/_components/common/StudioWrapper.server.tsx
Labels: feat

#40 feat(components/LoginModal): 로그인 API 연동
  src/app/_components/LoginModal/LoginModal.client.tsx
  yarn.lock
Labels: feat

#42 feat(ChannelPage): 커뮤니티 글 작성
  package-lock.json
  src/app/(route)/[channel]/page.tsx
  src/app/(route)/channel/[uid]/.gitkeep
  src/app/(route)/channel/[uid]/components/BoardInput.tsx
  src/app/(route)/channel/[uid]/components/ChannelProfile.tsx
  src/app/(route)/channel/[uid]/components/Post.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/channel/[uid]/page.tsx
  src/app/(route)/channel/[uid]/write/layout.tsx
  src/app/(route)/channel/[uid]/write/page.tsx
  tsconfig.json
Labels: feat, fix

#46 feat(studioPage, login): 네비게이션 디자인 추가 작업 및 로그인 미들웨어 구현
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/Navigation.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/SubMenus.tsx
  src/app/(route)/studio/[uid]/_components/common/MenuButtonBox.client.tsx
  src/app/_utils/studio/getMenuList.ts
  src/app/_utils/supabase/middleware.ts
  src/middleware.ts
Labels: feat, fix

#48 feat(studioPage): 네비게이션 라우트 할당 및 middleware 작업
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/Navigation.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/SubMenus.tsx
  src/app/(route)/studio/[uid]/_components/common/MenuButtonBox.client.tsx
  src/app/_utils/studio/getMenuList.ts
  src/app/_utils/supabase/middleware.ts
  src/middleware.ts
Labels: feat, fix

#52 Feat/studio/route
  public/studioPage/Lock.svg
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/_components/Block/Block.server.tsx
  src/app/(route)/studio/[uid]/_components/Popup/CheckBtn.client.tsx
  src/app/(route)/studio/[uid]/_components/common/Footer.tsx
  src/app/(route)/studio/[uid]/_components/common/StudioWrapper.server.tsx
  src/app/(route)/studio/page.tsx
Labels: feat

#53 feat(_hooks/streaming): Agora 미들웨어 훅 구현
  package.json
  src/app/_hooks/streaming/useAgoraClient.client.tsx
  src/app/_hooks/streaming/useAgoraMedia.client.tsx
  src/app/_hooks/streaming/useLiveStreamControl.client.tsx
  src/app/_hooks/streaming/useStudioStreamControl.client.ts
Labels: feat
