Repository 9oormthon-2523/Ezz, pull requests merged in 2025-02, with the labels that each got.

#150 fix(StudioPage): follower_details profile_img 속성값 오타 수정
  src/app/api/user/follow/[uid]/route.ts
Labels: fix

#153 Refactor(stores/live/store): livePage zustand 훅 통합
  src/app/(route)/live/[host_uid]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveBox.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveDetailsButton.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerOverlay.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerStateSign.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomVolume.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerButtons.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerHeader/PlayerHeader.client.tsx
  src/app/(route)/live/[host_uid]/layout.tsx
  src/app/(route)/live/[host_uid]/page.tsx
  src/app/(route)/live/[host_uid]/widget/Chat.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveDetails.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveStreamWrapper.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveTotalWrapper.clinet.tsx
  src/app/(route)/live/[host_uid]/widget/VideoPlayer.client.tsx
  src/app/(route)/live/[host_uid]/widget/_StreamingPage.client.tsx
  src/app/_hooks/live/useLiveManager.tsx
  src/app/_store/stores/live/useLiveControl.ts
  src/app/_store/stores/live/useScreenControl.ts
  src/app/_store/stores/live/useVideoControl.ts
  src/app/_types/live/liveType.ts
  src/app/_utils/live/db/getClinetInfo.server.ts
  src/app/_utils/live/db/getLiveInitDto.server.ts
  src/app/_utils/live/db/useLiveInfo.client.ts
  src/app/_utils/live/db/usePing.client.tsx
  src/app/_utils/live/local/throttle.client.ts
  src/app/_utils/live/local/useChatPositionUpdater.ts
  src/app/_utils/live/local/useFullScreenHandler.client.ts
  src/app/_utils/live/local/useOpacityAnimation.client.tsx
  src/app/_utils/live/local/useVideoPlayerHook.ts
Labels: refactor

#160 feat(studio): zod 스키마를 이용한 태그 문자 검증 구현
  package-lock.json
  package.json
  src/app/(route)/studio/[uid]/(route)/live/_components/Settings/CellComponents/CellTags.tsx
  src/app/_hooks/studio/useTagValidation.ts
Labels: feat

#164 fix(StudioPage): isFold 상태에 따른 버튼 UI 버그 수정
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/common/MenuButtonBox.client.tsx
Labels: fix

#161 Refactor/live hook
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomVolume.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerButtons.client.tsx
  src/app/(route)/live/[host_uid]/widget/VideoPlayer.client.tsx
  src/app/_hooks/live/client/useClinetAudience..client.tsx
  src/app/_hooks/live/client/useMediaPublish.client.tsx
  src/app/_hooks/live/media/useMediaControl.client.tsx
  src/app/_hooks/live/useLive.tsx
  src/app/_hooks/live/useLiveManager.tsx
  src/app/_store/stores/live/useLiveControl.ts
Labels: refactor

#167 fix(channelPage): 채널 페이지 팔로워 수 오류 수정
  src/app/(route)/channel/[uid]/components/ChannelProfile.tsx
  src/app/(route)/channel/[uid]/layout.tsx
Labels: fix, refactor

#173 fix(studio): 공지사항 리스트 컴포넌트 수정
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/NoticeItem.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget5.server.tsx
Labels: fix

#166 feat(supabase): supabase database type 정의
  package-lock.json
  package.json
  src/app/_utils/supabase/database.types.ts
Labels: feat

#185 Refactor(livePage-type) : 타입 개선
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/_types/live/liveType.ts
Labels: refactor

#184 feat(streaming-view): `/studio/[uid]/live` 페이지 사용성 개선을 위한 스트리밍 뷰 페이지 구현
  src/app/(route)/layout.tsx
  src/app/(route)/streaming-view/[uid]/layout.tsx
  src/app/(route)/streaming-view/[uid]/page.tsx
  src/app/(route)/streaming-view/page.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingArea/StreamingView.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingView.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/_components/ClientPortal.tsx
  src/app/_components/StreamingArea/ActionButton.client.tsx
  src/app/_components/StreamingArea/BeforeUnloadWrapper.client.tsx
  src/app/_components/StreamingArea/ExplainBtn.client.tsx
  src/app/_components/StreamingArea/MiniVideo.client.tsx
  src/app/_components/StreamingArea/StreamingButtonList.client.tsx
  src/app/_components/StreamingArea/StreamingStatus.client.tsx
  src/app/_components/StreamingArea/StreamingView.client.tsx
  src/app/_hooks/studio/audience/useAudienceCnt.tsx
  src/app/_hooks/studio/client/useStreamCleanup.client.ts
  src/app/_hooks/studio/useStudioManager.client.tsx
  src/app/_hooks/studio/worker/studioWorker.ts
  src/app/_hooks/studio/worker/useStreamingWorker.ts
  src/app/_styles/customChat.css
  src/app/_styles/studioPage.css
Labels: feat

#181 feat(channelPage): 삭제 전 확인 모달 추가
  src/app/(route)/channel/[uid]/components/Comment.tsx
  src/app/(route)/channel/[uid]/components/ConfirmModal.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
Labels: feat

#182 feat(channelPage): 채널 페이지 프로필 삭제 기능 추가
  src/app/(route)/channel/[uid]/settings/page.tsx
Labels: feat

#187 feat(channelPage): 팔로잉 목록 채널 검색 기능 추가
  src/app/(route)/channel/[uid]/components/SearchProfileInput.tsx
  src/app/(route)/channel/[uid]/follow/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
Labels: feat

#191 Feat(miniVideo/liveScreen): 미니 비디오 동작 개선
  src/app/_components/StreamingArea/MiniVideo.client.tsx
  src/app/_components/StreamingArea/StreamingButtonList.client.tsx
  src/app/_components/StreamingArea/StreamingView.client.tsx
Labels: feat

#196 Feat(mainPage):store 변경, 사용자 예외 처리,supabase-cli type 변경
  src/app/(route)/(main)/_components/NavBar/NavBar.client.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/live/[host_uid]/components/Wrapper/LiveTotalWrapper.clinet.tsx
  src/app/(route)/live/[host_uid]/widget/_StreamingPage.client.tsx
  src/app/_components/Header/ExpandNavButton.client.tsx
  src/app/_components/StreamList/card/StreamCard.server.tsx
  src/app/_hooks/streamList/useFetchStreamData.ts
  src/app/_store/queries/streamList/query.ts
  src/app/_store/stores/chat/chatStore.ts
  src/app/_store/stores/main/useNavToggle.client.ts
  src/app/_types/streamcard/streamcard.type.ts
  src/app/_utils/live/local/useVideoPlayerHook.ts
Labels: fix, refactor

#198 fix(studio): 태그 업데이트 후 삭제 시 UI 버그 수정
  src/app/_hooks/studio/useTagValidation.ts
Labels: fix

#200 refactor(channelPage): 채널 페이지 컴포넌트/훅 분리
  src/app/(route)/channel/[uid]/.gitkeep
  src/app/(route)/channel/[uid]/components/BoardInput.client.tsx
  src/app/(route)/channel/[uid]/components/ChannelProfile.server.tsx
  src/app/(route)/channel/[uid]/components/Comment.tsx
  src/app/(route)/channel/[uid]/components/Post.server.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/components/Comment.client.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/components/CommentDropdown.client.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/components/CommentInput.client.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/components/ConfirmModal.client.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/layout.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
  src/app/(route)/channel/[uid]/edit/[postid]/layout.tsx
  src/app/(route)/channel/[uid]/follow/components/Follow.Client.tsx
  src/app/(route)/channel/[uid]/follow/components/FollowChannel.server.tsx
  src/app/(route)/channel/[uid]/follow/components/SearchProfileInput.client.tsx
  src/app/(route)/channel/[uid]/follow/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/channel/[uid]/page.tsx
  src/app/(route)/channel/[uid]/settings/components/ProfileImage.client.tsx
  src/app/(route)/channel/[uid]/settings/layout.tsx
  src/app/(route)/channel/[uid]/settings/page.tsx
  src/app/(route)/channel/[uid]/write/components/WriteForm.client.tsx
  src/app/(route)/channel/[uid]/write/layout.tsx
  src/app/(route)/channel/[uid]/write/page.tsx
  src/app/_hooks/channel/detail/useComments.ts
  src/app/_hooks/channel/detail/usePost.ts
  src/app/_hooks/channel/follow/useFollowingUsers.ts
  src/app/_hooks/channel/useChannelData.ts
  src/app/_hooks/channel/useChannelPosts.ts
  src/app/_hooks/channel/useLoggedInUser.ts
  src/app/_hooks/channel/write/useFilePreview.ts
Labels: refactor
