Repository 9oormthon-2523/Ezz, pull requests merged in 2025-01, with the labels that each got.

#56 feat(studioPage): 로그인 유저 토큰을 이용한 헤더 프로필 구현
  next.config.ts
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/HeaderButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/_components/OutsideClickWrapper.client.tsx
Labels: feat

#61 feat(livePage/chat): 채팅 페이지 연동
  package.json
  src/app/(route)/chat/[uid]/page.tsx
  src/app/(route)/chat/page.tsx
  src/app/(route)/live/[id]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[id]/components/Chat/Input.client.tsx
  src/app/(route)/live/[id]/page.tsx
  src/app/(route)/live/[id]/widget/Chat.client.tsx
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/_components/Chat/Chat.tsx
  src/app/_components/Chat/MessageInput.tsx
  src/app/_components/Chat/MessageList.tsx
  src/app/_components/LoginModal/LoginModal.client.tsx
  src/app/_hooks/streaming/useAgoraClient.client.tsx
  src/app/_hooks/streaming/useAgoraMedia.client.tsx
  src/app/_hooks/streaming/useLiveStreamControl.client.tsx
  src/app/_hooks/streaming/useStudioStreamControl.client.ts
  src/app/_hooks/useChat.ts
  src/app/_store/chat/chatStore.ts
  src/app/_types/chat/Chat.ts
Labels: feat

#67 featI/studioPage/live/streaming): 호스트 스트리밍 기능 구현
  package.json
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingCoreBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/_hooks/studio/useStudioManager.client.tsx
Labels: feat

#68 feat(livePage): 챗 기능 연동 ,비디오 기능 연동, 및 코드 리팩토링
  next.config.ts
  src/app/(route)/chat/[uid]/page.tsx
  src/app/(route)/chat/page.tsx
  src/app/(route)/live/.gitkeep
  src/app/(route)/live/[id]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[id]/components/Chat/Input.client.tsx
  src/app/(route)/live/[id]/components/VideoPlayer/PlayerBottom/PlayerBottom.client.tsx
  src/app/(route)/live/[id]/components/VideoPlayer/PlayerBottom/PlayerBottomVolume.tsx
  src/app/(route)/live/[id]/components/VideoPlayer/PlayerBottom/PlayerButtons.client.tsx
  src/app/(route)/live/[id]/layout.tsx
  src/app/(route)/live/[id]/page.tsx
  src/app/(route)/live/[id]/utils/VideoPlayerHook.tsx
  src/app/(route)/live/[id]/widget/Chat.client.tsx
  src/app/(route)/live/[id]/widget/LiveStreamWrapper.client.tsx
  src/app/(route)/live/[id]/widget/VideoPlayer.client.tsx
  src/app/(route)/live/[id]/widget/Wrapper.clinet.tsx
  src/app/(route)/live/[id]/widget/_StreamingPage.client.tsx
  src/app/(route)/live/page.tsx
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/_components/Chat/Chat.tsx
  src/app/_components/Chat/MessageInput.tsx
  src/app/_components/Chat/MessageList.tsx
  src/app/_components/LoginModal/LoginModal.client.tsx
  src/app/_hooks/live/useLiveManager.tsx
  src/app/_hooks/streaming/useAgoraClient.client.tsx
  src/app/_hooks/streaming/useAgoraMedia.client.tsx
  src/app/_hooks/streaming/useLiveStreamControl.client.tsx
  src/app/_hooks/streaming/useStudioStreamControl.client.ts
  src/app/_hooks/useChat.ts
  src/app/_store/chat/chatStore.ts
  src/app/_store/live/useVideoControl.ts
  src/app/_types/chat/Chat.ts
Labels: feat, refactor

#78 refactor(studioPage/live/streaming): 리팩토링 및 기능 개선
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingCoreBtn.client.tsx
  src/app/_hooks/studio/client/clientUtils.client.ts
  src/app/_hooks/studio/client/useClient.client.ts
  src/app/_hooks/studio/media/audioControls.ts
  src/app/_hooks/studio/media/useMediaTrack.ts
  src/app/_hooks/studio/useStudioManager.client.tsx
Labels: refactor

#81 feat(ChannelPage): 채널 수정 페이지 (settings)
  next.config.ts
  src/app/(route)/channel/[uid]/settings/layout.tsx
  src/app/(route)/channel/[uid]/settings/page.tsx
Labels: feat

#84 feat(studioPage): studio/[uid]/live 스트리밍 기능, studio/[uid]/follower 페이지 구현
  next.config.ts
  package-lock.json
  package.json
  public/studioPage/Lock.svg
  public/studioPage/MyChannelFollower.svg
  public/studioPage/Search.svg
  src/app/(route)/layout.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/CountArea.client.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/SearchArea.client.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/UserColumn.server.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/UserFollowBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/UserTable.client.tsx
  src/app/(route)/studio/[uid]/(route)/follower/page.tsx
  src/app/(route)/studio/[uid]/(route)/layout.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingCoreBtn.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/(route)/studio/[uid]/_components/Block/Block.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/ExpandNavButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/HeaderButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/NavMenu.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/Navigation.client.tsx
  src/app/(route)/studio/[uid]/_components/Navigation/SubMenus.tsx
  src/app/(route)/studio/[uid]/_components/Popup/CheckBtn.client.tsx
  src/app/(route)/studio/[uid]/_components/common/ContentWrapper.client.tsx
  src/app/(route)/studio/[uid]/_components/common/Footer.tsx
  src/app/(route)/studio/[uid]/_components/common/MenuButtonBox.client.tsx
  src/app/(route)/studio/[uid]/_components/common/StudioWrapper.server.tsx
  src/app/(route)/studio/page.tsx
  src/app/_components/OutsideClickWrapper.client.tsx
  src/app/_hooks/studio/client/clientUtils.client.ts
  src/app/_hooks/studio/client/useClient.client.ts
  src/app/_hooks/studio/media/audioControls.ts
  src/app/_hooks/studio/media/useMediaTrack.ts
  src/app/_hooks/studio/useStudioManager.client.tsx
  src/app/_store/.gitkeep
  src/app/_store/context/useUid.tsx
  src/app/_store/queries/follow/mutation.ts
  src/app/_store/queries/follow/query.ts
  src/app/_store/stores/studio/useNavSizeToggle.client.ts
  src/app/_styles/globals.css
  src/app/_styles/studioPage.css
  src/app/_types/ISODate.type.ts
  src/app/_types/follow.type.ts
  src/app/_utils/common/elapsedTime.ts
  src/app/_utils/common/formatDate.ts
  src/app/_utils/query/TanstackQueryProvider.tsx
  src/app/api/user/follow/[uid]/route.ts
Labels: feat

#88 feat(api/route/callback): 카카오 로그인 시 public.users 테이블 업데이트 로직 추가
  next.config.ts
  src/app/_components/KakaoBtn.tsx
  src/app/api/auth/callback/route.ts
Labels: feat

#94 feat(ChannelPage): 동적 라우팅 수정
  next.config.ts
  public/channelPage/blank_profile.svg
  src/app/(route)/channel/[uid]/components/BoardInput.tsx
  src/app/(route)/channel/[uid]/components/ChannelProfile.tsx
  src/app/(route)/channel/[uid]/components/Post.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
  src/app/(route)/channel/[uid]/edit/[postid]/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/channel/[uid]/page.tsx
  src/app/(route)/channel/[uid]/settings/page.tsx
  src/app/(route)/channel/[uid]/write/page.tsx
  src/app/_components/Header/ProfileBtn.tsx
Labels: feat

#96 feat(livePage/dbLink): 라이브 페이지 DB 연동 및 시청자 수 카운팅 기능 추가
  next.config.ts
  src/app/(route)/live/[host_uid]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[host_uid]/components/Chat/Header.client.tsx
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveDetailComponents.client.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveDetailsButton.client.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveDetailsOptionButton.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerOverlay.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerStateSign.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottom.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomButton.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomVolume.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerButtons.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerHeader/PlayerHeader.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerHeader/PlayerHeaderButton.client.tsx
  src/app/(route)/live/[host_uid]/components/_ETC/liveBox.tsx
  src/app/(route)/live/[host_uid]/layout.tsx
  src/app/(route)/live/[host_uid]/liveType.ts
  src/app/(route)/live/[host_uid]/page.tsx
  src/app/(route)/live/[host_uid]/style.css
  src/app/(route)/live/[host_uid]/style/VideoPlayerStyle.ts
  src/app/(route)/live/[host_uid]/utils/db/getClinetInfo.server.ts
  src/app/(route)/live/[host_uid]/utils/db/getLiveInitDto.server.ts
  src/app/(route)/live/[host_uid]/utils/db/useLiveInfo.client.ts
  src/app/(route)/live/[host_uid]/utils/db/usePing.client.tsx
  src/app/(route)/live/[host_uid]/utils/local/useFullScreenHandler.client.ts
  src/app/(route)/live/[host_uid]/utils/local/useOpacityAnimation.client.tsx
  src/app/(route)/live/[host_uid]/utils/local/useVideoPlayerHook.ts
  src/app/(route)/live/[host_uid]/widget/Chat.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveDetails.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveStreamWrapper.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveTotalWrapper.clinet.tsx
  src/app/(route)/live/[host_uid]/widget/VideoPlayer.client.tsx
  src/app/(route)/live/[host_uid]/widget/_StreamingPage.client.tsx
  src/app/(route)/live/[id]/components/LiveDetails/LiveDetailsCategory.client.tsx
  src/app/(route)/live/[id]/components/LiveDetails/LiveDetailsHashTags.client.tsx
  src/app/(route)/live/[id]/components/LiveDetails/LiveDetailsNickName.client.tsx
  src/app/(route)/live/[id]/components/LiveDetails/LiveDetailsViewerStats.client.tsx
  src/app/(route)/live/[id]/page.tsx
  src/app/(route)/live/[id]/utils/getVideoRatio.ts
  src/app/(route)/live/[id]/widget/LiveDetails.client.tsx
  src/app/(route)/live/[id]/widget/VideoPlayer.client.tsx
  src/app/(route)/live/[id]/widget/_StreamingPage.client.tsx
  src/app/_hooks/live/useLiveManager.tsx
Labels: feat

#105 feat(studioPage): studioPage 전반적인 디자인 수정 및 live 페이지 DB, chat 연동
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget1.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget2.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget3.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget4.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/_components/widget/Widget5.server.tsx
  src/app/(route)/studio/[uid]/(route)/(dashboard)/page.tsx
  src/app/(route)/studio/[uid]/(route)/follower/_components/SearchArea.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/_hooks/studio/audience/useAudienceCnt.tsx
  src/app/_hooks/studio/useStudioManager.client.tsx
  src/app/_store/queries/streamingSettings/mutation.ts
  src/app/_styles/studioPage.css
  src/app/_utils/studio/getMenuList.ts
Labels: feat

#117 fix(useStudioManager/closeStream) : 라우팅 창 강제종료시 스트리밍 상태 db반영 및 빌드 에러 해결
  src/app/(route)/chat/[uid]/page.tsx
  src/app/(route)/chat/page.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerStateSign.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomButton.client.tsx
  src/app/(route)/live/[host_uid]/liveType.ts
  src/app/(route)/live/[host_uid]/utils/local/useOpacityAnimation.client.tsx
  src/app/_components/Header/Header.server.tsx
  src/app/_hooks/live/useLiveManager.tsx
  src/app/_hooks/studio/audience/useAudienceCnt.tsx
  src/app/_hooks/studio/client/clientUtils.client.ts
  src/app/_hooks/studio/client/useClient.client.ts
  src/app/_hooks/studio/client/useStreamCleanup.client.ts
  src/app/_hooks/studio/media/audioControls.ts
  src/app/_hooks/studio/media/useMediaTrack.ts
  src/app/_hooks/studio/useStudioManager.client.tsx
  src/app/api/user/streamingcleanup/route.ts
Labels: fix

#121 fix(env): env BASE_URL 추가
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/_store/queries/follow/query.ts
  src/app/_store/queries/streamingSettings/query.ts
Labels: fix

#122 fix(login): 로그인 리다이렉트 값 수정
  src/app/api/auth/callback/route.ts
Labels: fix

#119 feat(ChannelPage): 댓글 CRUD 구현
  public/channelPage/delete.svg
  public/channelPage/edit.svg
  public/channelPage/more_vert.svg
  src/app/(route)/channel/[uid]/components/Comment.tsx
  src/app/(route)/channel/[uid]/components/CommentInput.tsx
  src/app/(route)/channel/[uid]/components/Post.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
Labels: feat

#124 feat(livePage): 팔로워 및 채팅 기능 추가
  package-lock.json
  package.json
  src/app/(route)/live/[host_uid]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/(route)/live/[host_uid]/components/LiveDetails/LiveDetailsButton.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerOverlay.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/ETC/PlayerStateSign.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomButton.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerBottomVolume.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerBottom/PlayerButtons.client.tsx
  src/app/(route)/live/[host_uid]/components/VideoPlayer/PlayerHeader/PlayerHeader.client.tsx
  src/app/(route)/live/[host_uid]/utils/db/useLiveInfo.client.ts
  src/app/(route)/live/[host_uid]/utils/local/useFullScreenHandler.client.ts
  src/app/(route)/live/[host_uid]/utils/local/useVideoPlayerHook.ts
  src/app/(route)/live/[host_uid]/widget/Chat.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveDetails.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveStreamWrapper.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveTotalWrapper.clinet.tsx
  src/app/(route)/live/[host_uid]/widget/VideoPlayer.client.tsx
  src/app/(route)/live/[host_uid]/widget/_StreamingPage.client.tsx
  src/app/(route)/live/[id]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/page.tsx
  src/app/_components/SVGIcon.server.tsx
  src/app/_hooks/live/useLiveManager.tsx
  src/app/_hooks/studio/audience/useAudienceCnt.tsx
  src/app/_hooks/useChat.ts
  src/app/_store/stores/live/useScreenControl.ts
  src/app/_store/stores/live/useVideoControl.ts
  src/app/_utils/chat/hashColor.ts
Labels: feat

#125 fix(ChannelPage): 채널 세팅 페이지 오류 수정
  src/app/(route)/channel/[uid]/settings/page.tsx
Labels: fix

#128 fix: 로그인 조건문 분기 처리, 이미지 업로드 방식 수정
  src/app/_store/queries/streamingSettings/mutation.ts
  src/app/api/auth/callback/route.ts
Labels: bug, fix

#131 fix(fix/livePage/chat): 채팅 기능 버그 픽스 및 추가 기능 추가
  public/livePage/Chat/arrowBottom.svg
  src/app/(route)/live/[host_uid]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/(route)/live/[host_uid]/utils/local/throttle.client.ts
Labels: fix

#132 feat(ChannelPage): 채널 팔로잉 목록 탭 추가
  public/channelPage/heart.svg
  public/channelPage/no_content.svg
  public/channelPage/setting.svg
  public/channelPage/video.svg
  src/app/(route)/channel/[uid]/components/BoardInput.tsx
  src/app/(route)/channel/[uid]/components/ChannelProfile.tsx
  src/app/(route)/channel/[uid]/components/FollowChannel.tsx
  src/app/(route)/channel/[uid]/components/Post.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
  src/app/(route)/channel/[uid]/edit/[postid]/page.tsx
  src/app/(route)/channel/[uid]/follow/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/channel/[uid]/page.tsx
  src/app/(route)/channel/[uid]/write/page.tsx
Labels: feat, fix

#140 Fix(livePage/bug): 테스트 버그 픽스 및 일부 기능 개선
  src/app/(route)/live/[host_uid]/components/Chat/ChatWindow.client.tsx
  src/app/(route)/live/[host_uid]/widget/LiveDetails.client.tsx
  src/app/(route)/live/[host_uid]/widget/VideoPlayer.client.tsx
  src/app/_hooks/live/useLiveManager.tsx
Labels: fix

#141 Fix(channelPage ): 테스트 버그 및 기능 개선
  public/channelPage/Invisible.svg
  src/app/(route)/channel/[uid]/components/ChannelProfile.tsx
  src/app/(route)/channel/[uid]/components/Comment.tsx
  src/app/(route)/channel/[uid]/detail/[postid]/page.tsx
  src/app/(route)/channel/[uid]/layout.tsx
  src/app/(route)/channel/[uid]/settings/page.tsx
Labels: fix

#142 fix(livePage/bug): 오디오 기능/크로스 브라우징 문제 해결
  src/app/(route)/live/[host_uid]/components/Chat/Input.client.tsx
  src/app/(route)/studio/[uid]/(route)/live/_components/StreamingArea/StreamingButtonList.client.tsx
  src/app/_hooks/studio/media/useMediaTrack.ts
Labels: bug, fix

#143 fix(studioPage): 스튜디오 페이지 프로필 users 테이블과 연동으로 수정
  src/app/(route)/studio/[uid]/_components/Header/Header.server.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileButton.client.tsx
  src/app/(route)/studio/[uid]/_components/Header/ProfileMenu.server.tsx
  src/app/api/auth/user/route.ts
Labels: fix
